### ISSUE TITLE
what's the differences between 3288 and 3399 usb device which influence the rockusb?

### ISSUE THREAD

**Issue by 54shady** [rockchip-linux/rkdeveloptool#35]
I write myself a tool which copy from the rkflashtool with python using libusb1
see my github for the source code (branch setup or standlone)
https://github.com/54shady/flashtool

Now, the tool is supoort rk3288 nicely, but when I try to use it on rk3399, i got the error below?
can't figure out why the urb submit error happen?

`Found devices
0x2207:0x330c
EP_IN:129
EP_OUT:1
libusb: error [submit_bulk_transfer] submiturb failed error -1 errno=2
Traceback (most recent call last):
  File "/usr/local/bin/flashtool", line 9, in <module>
    load_entry_point('flashtool==1.0.0', 'console_scripts', 'flashtool')()
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/__init__.py", line 10, in main
    sys.exit(app.main(sys.argv[1:]))
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/main.py", line 149, in main
    with self.get_operation() as op:
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/main.py", line 244, in get_operation
    with self.get_rkoperation() as op:
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/main.py", line 265, in get_rkoperation
    return RkOperation(self.logger, self.bus_id, self.dev_id, self.chk_rw)
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/vendor/rkusb.py", line 255, in __init__
    self.init_device()
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/vendor/rkusb.py", line 273, in init_device
    self.__rk_device_init()
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/vendor/rkusb.py", line 265, in __rk_device_init
    self.send_cbw(bulk_cb_wrap("TEST_UNIT_READY"))
  File "/home/zeroway/.local/lib/python2.7/site-packages/flashtool/vendor/rkusb.py", line 348, in send_cbw
    self.__dev_handle.bulkWrite(self.EP_OUT, cbw)
  File "/home/zeroway/.local/lib/python2.7/site-packages/usb1/__init__.py", line 1537, in bulkWrite
    return self._bulkTransfer(endpoint, data, sizeof(data), timeout)
  File "/home/zeroway/.local/lib/python2.7/site-packages/usb1/__init__.py", line 1509, in _bulkTransfer
    self.__handle, endpoint, data, length, byref(transferred), timeout,
  File "/home/zeroway/.local/lib/python2.7/site-packages/usb1/__init__.py", line 133, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/zeroway/.local/lib/python2.7/site-packages/usb1/__init__.py", line 125, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorIO: LIBUSB_ERROR_IO [-1]
`
currently don't konw why, and what happend about the "usb1.USBErrorIO: LIBUSB_ERROR_IO"

anyone can give me some suggest?

**Comment by keveryang** [comment]
Maybe you should decode the endpoint info from device configuration instead of hard code for it.

**Comment by bubbadestroy** [comment]
> Maybe you should decode the endpoint info from device configuration instead of hard code for it.

bubba destroy!
